# Generated by Django 3.0.5 on 2020-05-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_name', models.CharField(max_length=20)),
                ('exproduct_name', models.CharField(max_length=15)),
                ('inproduct_name', models.CharField(max_length=15)),
                ('bin_no', models.SmallIntegerField(max_length=3)),
                ('spec_name', models.CharField(max_length=7)),
                ('wld1_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wld1_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lop1_max', models.SmallIntegerField(max_length=4)),
                ('lop1_min', models.SmallIntegerField(max_length=4)),
                ('vf1_max', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vf1_min', models.DecimalField(decimal_places=2, max_digits=3)),
                ('code', models.CharField(max_length=2)),
                ('vfspec', models.CharField(max_length=3)),
                ('ivspec', models.CharField(max_length=3)),
                ('wdspec', models.CharField(max_length=3)),
                ('prod_no', models.CharField(max_length=3)),
                ('grade', models.CharField(max_length=1)),
                ('process_code', models.CharField(max_length=1)),
                ('lop1_avg', models.CharField(max_length=7)),
            ],
        ),
    ]
