# Generated by Django 3.0.5 on 2020-05-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bin_no',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='lop1_max',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='lop1_min',
            field=models.SmallIntegerField(),
        ),
    ]
