# Generated by Django 3.0.5 on 2020-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binchecker', '0003_auto_20200505_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lop1_avg',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
