# Generated by Django 3.0.5 on 2020-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binchecker', '0004_auto_20200505_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='process_code',
            field=models.CharField(max_length=3),
        ),
    ]
