# Generated by Django 3.0.5 on 2020-05-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binchecker', '0005_auto_20200505_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lop1_avg',
        ),
        migrations.AddField(
            model_name='product',
            name='lop1_avgmax',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lop1_avgmin',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
